### ISSUE TITLE
Name of the shape

### ISSUE THREAD

**Issue by EmidioStani** [veleda/shacl-wiki#8]
In relation to the shape in the example:
https://kvistgaard.github.io/shacl/#/page/6492a456-8ca0-42c0-a6a7-73a4c40ed59b

I would either:

- call it "EnglishPrefLabelConstraint" as the message refers to English label and not Spanish
or
- change the message to Spanish since the SPARQL query tests for Spanish label.

**Comment by kvistgaard** [comment]
Thanks. Fixed.
